apiVersion: k8s.starter.org/v1alpha1
kind: KubernetesCluster
metadata:
  name: test123
  namespace: default
spec:
  id: test123
  parameters:
    nodes:
      count: 1
      size: small
    services:
      operators:
        prometheus:
          version: "34.5.1"
  writeConnectionSecretToRef:
    name: test123-kubeconfig
