apiVersion: k8s.starter.org/v1alpha1
kind: KubernetesCluster
metadata:
  name: create-cluster-dev
  namespace: default
spec:
  id: create-cluster-dev
  parameters:
    nodes:
      count: 1
      size: small
    services:
      operators:
        prometheus:
          version: "34.5.1"
  writeConnectionSecretToRef:
    name: create-cluster-dev-kubeconfig
