apiVersion: k8s.starter.org/v1alpha1
kind: KubernetesCluster
metadata:
  name: deny-test
  namespace: default
spec:
  id: deny-test
  parameters:
    nodes:
      count: 1
      size: small
    services:
      operators:
        prometheus:
          version: "34.5.1"
  writeConnectionSecretToRef:
    name: deny-test-kubeconfig
