apiVersion: k8s.starter.org/v1alpha1
kind: KubernetesCluster
metadata:
  name: final-request
  namespace: default
spec:
  id: final-request
  parameters:
    nodes:
      count: 1
      size: small
    services:
      operators:
        prometheus:
          version: "34.5.1"
  writeConnectionSecretToRef:
    name: final-request-kubeconfig
