apiVersion: k8s.starter.org/v1alpha1
kind: KubernetesCluster
metadata:
  name: matans-test-cluster
  namespace: default
spec:
  id: matans-test-cluster
  parameters:
    nodes:
      count: 1
      size: small
    services:
      operators:
        prometheus:
          version: "34.5.1"
  writeConnectionSecretToRef:
    name: matans-test-cluster-kubeconfig
