apiVersion: k8s.starter.org/v1alpha1
kind: KubernetesCluster
metadata:
  name: request-cluster
  namespace: default
spec:
  id: request-cluster
  parameters:
    nodes:
      count: 3
      size: medium
    services:
      operators:
        prometheus:
          version: "34.5.1"
  writeConnectionSecretToRef:
    name: request-cluster-kubeconfig
