apiVersion: k8s.starter.org/v1alpha1
kind: KubernetesCluster
metadata:
  name: roni-cluster
  namespace: default
spec:
  id: roni-cluster
  parameters:
    nodes:
      count: 1
      size: small
    services:
      operators:
        prometheus:
          version: "34.5.1"
  writeConnectionSecretToRef:
    name: roni-cluster-kubeconfig
