apiVersion: k8s.starter.org/v1alpha1
kind: KubernetesCluster
metadata:
  name: sabage
  namespace: default
spec:
  id: sabage
  parameters:
    nodes:
      count: 3
      size: small
    services:
      operators:
        prometheus:
          version: "34.5.1"
  writeConnectionSecretToRef:
    name: sabage-kubeconfig
