apiVersion: k8s.starter.org/v1alpha1
kind: KubernetesCluster
metadata:
  name: test3
  namespace: default
spec:
  id: test3
  parameters:
    nodes:
      count: 2
      size: small
    services:
      operators:
        prometheus:
          version: "34.5.1"
  writeConnectionSecretToRef:
    name: test3-kubeconfig
