apiVersion: k8s.starter.org/v1alpha1
kind: KubernetesCluster
metadata:
  name: test2
  namespace: default
spec:
  id: test2
  parameters:
    nodes:
      count: 2
      size: small
    services:
      operators:
        prometheus:
          version: "34.5.1"
  writeConnectionSecretToRef:
    name: test2-kubeconfig
