name: Apply Cluster changes

on:
  workflow_call:

jobs:
  apply-clusters:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true
          ref: main
      - name: Install Kubectl
        uses: azure/setup-kubectl@v3
        id: install-kubectl
      - name: Install Upbound CLI
        run: |
          curl -sL "https://cli.upbound.io" | sh
          sudo mv up /usr/local/bin/
      - name: Connect to Upbound using CLI an apply manifests to all of the control planes
        run: |
          up login -t ${{ secrets.UPBOUND_TOKEN }}
          for CONTROL_PLANE in */ ; do
            # Remove trailing slash to get the clean cluster name
            CONTROL_PLANE=${CONTROL_PLANE%/}
          
            # Get the kube config for the specific control plane
            up ctp kubeconfig get -a "$CONTROL_PLANE" -f kubeconfig.yaml --token ${{ secrets.UPBOUND_TOKEN }}
            up ctp kubeconfig get -a port "$CONTROL_PLANE" -f kubeconfig.yaml --token ${{ secrets.UPBOUND_TOKEN }}
          done

      - name: Apply clusters to Upbound
        run: |
          kubectl --kubeconfig kubeconfig.yaml apply -f .up/clusters/ --recursive
      
  
